
service: ekitab
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1

functions:
  hello:
    handler: src/handler.index
    timeout: 60 # seconds
    memorySize: 128 # minimum we can set
